[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bevy = "0.14.2"
bevy_egui = "0.29.0"
egui = "0.28.1"
rfd = "0.15.0"
futures-lite = "2.3.0"
mdl = { path = "../mdl" }