[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bot = { path = "../bot" }
state = { path = "../state" }
commands = { path = "../commands" }
mdl = { path = "../mdl" }
nbt = { path = "../nbt" }

[dev-dependencies]
glob = "0.3.1"